### ISSUE TITLE
Postinstall assumes jspm

### ISSUE THREAD

**Issue by adamcarheden** [HuasoFoundries/systemjs-riot#4]
Your post-install script, `jspm install`, assumes jspm is installed. It's listed as a dev dependency, so it's not pulled in when I run `npm install systemjs-riot`. I suspect it should be listed as a dependency. Or, since it appears to just be doing something with the example/ directory, possibly making that an optional script rather than a postinstall. Or perhaps that should be built as part of the build process and committed precompiled to github. Or maybe the requirejs example in README.md just needs to be updated to install jspm manually first.

At any rate, here's what I get following the tutorial:
$ npm install systemjs-riot
...
sh: 1: jspm: not found
....
npm ERR! Tell the author that this fails on your system:
npm ERR!     jspm install
...

Running `npm install jspm` first makes everything work as expected.

**Comment by ffflabs** [comment]
@acarheden thank you, and I'm sorry I didn't see this sooner. 

You're right, I didn't consider the fact that using this loader with RequireJS would break. 

jspm is only needed for testing, so I moved the `jspm install` to the test task of Makefile.
