### ISSUE TITLE
Locating compilation errors

### ISSUE THREAD

**Issue by nevf** [HuasoFoundries/systemjs-riot#6]
@amenadiel  Thanks for creating systemjs-riot. Up until now I've been using `riot -w` to compile .tag files, but this is definitely better.

However when there is a problem with JS code in a .tag file, you only get an error at the top level of the file, with nothing to indicate the actual error. I'm using Chrome in case that is relevant.

I can go back and use riot to compile the file and then run `eslint` however this is a bit messy.

Do you have any suggestions for a more streamlined workflow?

**Comment by ffflabs** [comment]
Well, this isn't a bug from this plugin. I'm using  ESLint with riot plugin is you want to try it
